name: Rust CI Pipeline

on: [push]

env:
  DOCKER_IMAGE_NAME: ""

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write
  packages: write
  actions: read
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Run Custom Rust CI action
      uses: ./.github/actions/build
      with: 
        github_token: ${{ secrets.GITHUB_TOKEN }}
        gitleaks_token: ${{ secrets.GITLEAKS_TOKEN }}

  test:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Test Dockerfile 
      uses: ./.github/actions/test
      with:
        docker_repo_name: ${{ env.DOCKER_IMAGE_NAME || github.event.repository.name }}

  deploy:
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Deploy Dockerfile 
      if: ${{ github.ref_name == 'main' && github.event_name == 'push' }}
      uses: ./.github/actions/deploy
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        docker_repo_name: ${{ env.DOCKER_IMAGE_NAME || github.event.repository.name }}